name: Fix password hash
on: workflow_dispatch

jobs:
  fix-password:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: custom-v2
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Fix password hash
        run: |
          sed -i 's/"Aa123456."/"0198d738abd01713fc6497c05c62c09f5bf487907d4f8b20124fba83a447cee033"/g' src/config.rs
      
      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add src/config.rs
          git commit -m "Fix password hash"
          git push origin custom-v2
          


